#######VARS#######
variable "project"                  { description = "For Metadata Tags" }
variable "subnet_ids_rds"           { description = "Multi Subnet Placement" }
variable "identifier"               { description = "DB Identifier" }
variable "storage_type"             { description = "DB Storage Type" }
variable "db_engine"                { description = "DB Engine Type" }
variable "allocated_storage"        { description = "DB Storage Size" }
variable "rds_engine_version"       { description = "RDS Engine Version" }
variable "parameter_group_name"     { description = "RDS Parameter Group" }
variable "instance_class"           { description = "DB Instance Size" }
variable "username"                 { description = "DB Admin Username" }

######OUTPUT######
output "rds_endpoint"   { value = aws_db_instance.rds.endpoint }

##CREATES Radon Pass and Store them in Secret Manager
resource "random_password" "rds-admin" {
  length              = 24
  special             = false
}
resource "aws_secretsmanager_secret" "rds-admin" {
  name                = "${terraform.workspace}-${var.project}/rds-${var.identifier}-admin"
  description         = "admin username for mysql rds generated by terraform pipeline"
  tags = {
    PROJECT     = var.project
    WORKSPACE   = "${terraform.workspace}"
  }
}
resource "aws_secretsmanager_secret_version" "rds-admin" {
  secret_id     = aws_secretsmanager_secret.rds-admin.id
  secret_string = random_password.rds-admin.result
}

##Create Subnet Group for RDS
resource "aws_db_subnet_group" "data-rds" {
  name          = "data-subnet-rds"
  subnet_ids    = var.subnet_ids_rds
  tags = {
    PROJECT     = var.project
    WORKSPACE   = "${terraform.workspace}"
  }
}

##Create RDS Instance
resource "aws_db_instance" "rds" {
  name                 = "${terraform.workspace}-${var.identifier}"
  identifier           = "${terraform.workspace}-${var.identifier}"
  storage_type         = var.storage_type
  engine               = var.db_engine
  allocated_storage    = var.allocated_storage
  engine_version       = var.rds_engine_version
  parameter_group_name = var.parameter_group_name
  instance_class       = var.instance_class
  username             = var.username
  password             = random_password.rds-admin.result
  db_subnet_group_name = aws_db_subnet_group.data-rds.id
  storage_encrypted    = false
  skip_final_snapshot  = true
  publicly_accessible  = false
  multi_az             = true
  tags = {
    Name        = "${terraform.workspace}-${var.identifier}-mysql"
    PROJECT     = var.project
    WORKSPACE   = "${terraform.workspace}"
  }
  #vpc_security_group_ids = [
  #  var.sec_grp_rds,
  #]
}